In [6]:
print("komórka testowa")
t = 34.564
w = 5

komórka testowa


In [7]:
t*w

172.82

To jest pierwszy **notebook** - testujemy <span style="color:red; font-size:14pt;">Datalore</span> Dalsza częśc

In [8]:
200*w

1000

In [10]:
import datetime
data = (datetime.date(2024, 12, 16), datetime.date(2024, 12, 19))

In [11]:
data

(datetime.date(2024, 12, 16), datetime.date(2024, 12, 19))

In [15]:
wartA = 12

In [14]:
wartA - 1.22

10.78

In [17]:
import numpy as np

In [18]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.empty(14)

array([4.77751342e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000])

In [23]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [24]:
zlista = [4,24,56,343,3,4,5,6,6,7,45,2]
print(zlista)
print(type(zlista))

[4, 24, 56, 343, 3, 4, 5, 6, 6, 7, 45, 2]
<class 'list'>


In [25]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[  4  24  56 343   3   4   5   6   6   7  45   2]
<class 'numpy.ndarray'>


In [26]:
kl = (45,24,1,6,7,98,65,32,42,23)

npkl = np.array(kl)
npkl

array([45, 24, 1, 6, 7, 98, 65, 32, 42, 23])

In [27]:
npkl.sort()

In [28]:
npkl

array([ 1, 6, 7, 23, 24, 32, 42, 45, 65, 98])