In [2]:
print("komórka testowa")
t = 34.564
w = 5

komórka testowa


In [3]:
t*w

172.82

To jest pierwszy **notebook** - testujemy <span style="color:red; font-size:14pt;">Datalore</span> Dalsza częśc

In [4]:
200*w

1000

In [5]:
import datetime
data = (datetime.date(2024, 12, 16), datetime.date(2024, 12, 19))

In [6]:
data

(datetime.date(2024, 12, 16), datetime.date(2024, 12, 19))

In [7]:
wartA = 12

In [8]:
wartA - 1.22

10.78

In [9]:
import numpy as np

In [10]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.empty(14)

array([5.35589109e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000])

In [12]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [13]:
zlista = [4,24,56,343,3,4,5,6,6,7,45,2]
print(zlista)
print(type(zlista))

[4, 24, 56, 343, 3, 4, 5, 6, 6, 7, 45, 2]
<class 'list'>


In [14]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[  4  24  56 343   3   4   5   6   6   7  45   2]
<class 'numpy.ndarray'>


In [15]:
kl = (45,24,1,6,7,98,65,32,42,23)

npkl = np.array(kl)
npkl

array([45, 24, 1, 6, 7, 98, 65, 32, 42, 23])

In [16]:
npkl.sort()

In [17]:
npkl

array([ 1, 6, 7, 23, 24, 32, 42, 45, 65, 98])

In [18]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [19]:
l1 = [2,4,6,7]
l2 = [5,6,78,9]
l3 = [112,89,12,44]

In [20]:
l = l1+l2+l3
l

[2, 4, 6, 7, 5, 6, 78, 9, 112, 89, 12, 44]

In [21]:
npl1 = np.array(l1)
npl2 = np.array(l2)
npl3 = np.array(l3)

In [22]:
npl= npl1 + npl2 + npl3
npl

array([119, 99, 96, 60])

In [23]:
a = np.concatenate((npl1,npl2,npl3))
a

array([ 2, 4, 6, 7, 5, 6, 78, 9, 112, 89, 12, 44])

In [24]:
z1 = [[2,4],[7,4]]
nz1 = np.array([[13,6],[1,6]])

In [25]:
z1

[[2, 4], [7, 4]]

In [26]:
nz1

array([[13, 6],
 [ 1, 6]])

In [27]:
z1[0][1]

4

In [28]:
nz1[0][1]

6

In [29]:
nz1[0,1]

6

In [35]:
x = np.array([[1,3],[3,5]])
y = np.array([[2,-4],[1,1]])

In [36]:
x*y

array([[ 2, -12],
 [ 3, 5]])

In [38]:
p = np.concatenate((x,y),axis=0)
p

array([[ 1, 3],
 [ 3, 5],
 [ 2, -4],
 [ 1, 1]])

In [39]:
p.T

array([[ 1, 3, 2, 1],
 [ 3, 5, -4, 1]])

In [40]:
prosta = np.arange(12)
prosta

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [46]:
fp = prosta.reshape(3,4)
fp

array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11]])

In [47]:
fp.shape

(3, 4)

In [49]:
drugaprosta = fp.reshape(12)
drugaprosta

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [50]:
mc = np.array([[2,3],[4,5],[9,9]])
mc

array([[2, 3],
 [4, 5],
 [9, 9]])

In [51]:
mc.shape

(3, 2)

In [52]:
w1 = mc.reshape(6)
w1

array([2, 3, 4, 5, 9, 9])

In [53]:
w2 = np.array([5,5,2,6,8,2,12,34,8])
w12 = np.concatenate((w1,w2))
w12

array([ 2, 3, 4, 5, 9, 9, 5, 5, 2, 6, 8, 2, 12, 34, 8])

In [54]:
w12.shape

(15,)

In [55]:
mc15 = w12.reshape(3,5)
mc15

array([[ 2, 3, 4, 5, 9],
 [ 9, 5, 5, 2, 6],
 [ 8, 2, 12, 34, 8]])

In [57]:
mc15[:2]

array([[2, 3, 4, 5, 9],
 [9, 5, 5, 2, 6]])

In [69]:
#filtorwanie danych wektora w12

start =enumerate(w12)

In [66]:
for i,v in enumerate(w12):
    print(f"{i} -> {v}")

0 -> 2
1 -> 3
2 -> 4
3 -> 5
4 -> 9
5 -> 9
6 -> 5
7 -> 5
8 -> 2
9 -> 6
10 -> 8
11 -> 2
12 -> 12
13 -> 34
14 -> 8


In [72]:
wynik = enumerate(w12[w12<5])
wynik

In [63]:
for i,var in wynik:
    print(f"indeks {i} -> {var}")

indeks 0 -> 2
indeks 1 -> 3
indeks 2 -> 4
indeks 3 -> 2
indeks 4 -> 2


In [60]:
w12[3:6]

array([5, 9, 9])

In [73]:
pc = (w12>12)
w12[pc]

array([34])

In [74]:
pv = (w12%2==0)
w12[pv]

array([ 2, 4, 2, 6, 8, 2, 12, 34, 8])

In [76]:
vb = w12[(w12>2)&(w12<7)]
vb

array([3, 4, 5, 5, 5, 6])

In [77]:
#operacje arytmetyczne na wektorach
#CTRL + D - powielenie linii lub bloków tekstu
wk1 = np.array([1,3,8])
wk2 = np.array([1,1,2])
wk3 = np.array([2,3,2])

In [78]:
wk1 - wk2

array([0, 2, 6])

In [79]:
wk1+wk2

array([ 2, 4, 10])

In [80]:
wk1*wk2*wk3

array([ 2, 9, 32])

In [81]:
wk1*1.2567

array([ 1.2567, 3.7701, 10.0536])

In [83]:
np.mean(wk1)

4.0

In [84]:
np.std(wk2)

0.4714045207910317

In [85]:
p90 = np.percentile(wk2,90)
p90

1.8

In [86]:
wynik =(wk1+wk2)*wk3
wynik

array([ 4, 12, 20])

In [87]:
print(f"wartosc najmniejsza: {wynik.min()}")
print(f"wartosc największa: {wynik.max()}")
print(f"wartosc średnia: {wynik.mean()}")

wartosc najmniejsza: 4
wartosc największa: 20
wartosc średnia: 12.0
