In [1]:
print("komórka testowa")
t = 34.564
w = 5

komórka testowa


In [2]:
t*w

172.82

To jest pierwszy **notebook** - testujemy <span style="color:red; font-size:14pt;">Datalore</span> Dalsza częśc

In [3]:
200*w

1000

In [4]:
import datetime
data = (datetime.date(2024, 12, 16), datetime.date(2024, 12, 19))

In [5]:
data

(datetime.date(2024, 12, 16), datetime.date(2024, 12, 19))

In [6]:
wartA = 12

In [7]:
wartA - 1.22

10.78

In [8]:
import numpy as np

In [9]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.empty(14)

array([4.78367076e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000])

In [11]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [12]:
zlista = [4,24,56,343,3,4,5,6,6,7,45,2]
print(zlista)
print(type(zlista))

[4, 24, 56, 343, 3, 4, 5, 6, 6, 7, 45, 2]
<class 'list'>


In [13]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[  4  24  56 343   3   4   5   6   6   7  45   2]
<class 'numpy.ndarray'>


In [14]:
kl = (45,24,1,6,7,98,65,32,42,23)

npkl = np.array(kl)
npkl

array([45, 24, 1, 6, 7, 98, 65, 32, 42, 23])

In [15]:
npkl.sort()

In [16]:
npkl

array([ 1, 6, 7, 23, 24, 32, 42, 45, 65, 98])

In [17]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [18]:
l1 = [2,4,6,7]
l2 = [5,6,78,9]
l3 = [112,89,12,44]

In [19]:
l = l1+l2+l3
l

[2, 4, 6, 7, 5, 6, 78, 9, 112, 89, 12, 44]

In [20]:
npl1 = np.array(l1)
npl2 = np.array(l2)
npl3 = np.array(l3)

In [21]:
npl= npl1 + npl2 + npl3
npl

array([119, 99, 96, 60])

In [23]:
a = np.concatenate((npl1,npl2,npl3))
a

array([ 2, 4, 6, 7, 5, 6, 78, 9, 112, 89, 12, 44])

In [24]:
z1 = [[2,4],[7,4]]
nz1 = np.array([[13,6],[1,6]])

In [25]:
z1

[[2, 4], [7, 4]]

In [27]:
z1[0][1]

4

In [29]:
nz1[0][1]

6

In [31]:
nz1[0,1]

6