In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [4]:
arr = np.random.randn(6,3)
arr

array([[ 0.1483587 , -0.3815826 , 1.42060514],
 [ 3.09639957, -1.75732755, -0.48391347],
 [ 0.29307412, -0.239712 , -0.3912642 ],
 [ 0.41617906, 0.32311851, -0.63495047],
 [-0.7383266 , -0.45037073, -0.44963039],
 [ 0.09890636, 0.67104603, 0.60591782]])

In [6]:
arr.T

array([[ 0.1483587 , 3.09639957, 0.29307412, 0.41617906, -0.7383266 ,
 0.09890636],
 [-0.3815826 , -1.75732755, -0.239712 , 0.32311851, -0.45037073,
 0.67104603],
 [ 1.42060514, -0.48391347, -0.3912642 , -0.63495047, -0.44963039,
 0.60591782]])

In [5]:
np.dot(arr.T,arr)

array([[10.42370667, -5.03488617, -1.27464964],
 [-5.03488617, 4.04880939, 0.80604185],
 [-1.27464964, 0.80604185, 3.37784487]])

In [8]:
tens = np.arange(27).reshape(3,3,3)
tens

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
tens.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [11]:
tens.transpose(2,0,1)

array([[[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]],

       [[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25]],

       [[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]]])

In [12]:
tab5D = np.arange(240).reshape((2,2,4,5,3))
tab5D

array([[[[[  0,   1,   2],
          [  3,   4,   5],
          [  6,   7,   8],
          [  9,  10,  11],
          [ 12,  13,  14]],

         [[ 15,  16,  17],
          [ 18,  19,  20],
          [ 21,  22,  23],
          [ 24,  25,  26],
          [ 27,  28,  29]],

         [[ 30,  31,  32],
          [ 33,  34,  35],
          [ 36,  37,  38],
          [ 39,  40,  41],
          [ 42,  43,  44]],

         [[ 45,  46,  47],
          [ 48,  49,  50],
          [ 51,  52,  53],
          [ 54,  55,  56],
          [ 57,  58,  59]]],


        [[[ 60,  61,  62],
          [ 63,  64,  65],
          [ 66,  67,  68],
          [ 69,  70,  71],
          [ 72,  73,  74]],

         [[ 75,  76,  77],
          [ 78,  79,  80],
          [ 81,  82,  83],
          [ 84,  85,  86],
          [ 87,  88,  89]],

         [[ 90,  91,  92],
          [ 93,  94,  95],
          [ 96,  97,  98],
          [ 99, 100, 101],
          [102, 103, 104]],

         [[105, 106, 107],
          [1

In [13]:
#funkcje uniwersalne
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.sqrt(arr)

array([0. , 1. , 1.41421356, 1.73205081, 2. ,
 2.23606798, 2.44948974, 2.64575131, 2.82842712, 3. ])

In [17]:
# import math
# math.sqrt(arr)

In [18]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
 5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
 2.98095799e+03, 8.10308393e+03])